from django.urls import path
from . import views
urlpatterns=[
    path('',views.index,name='index'),
    path('registration',views.registration,name='registration'),
    path('login',views.login,name='login'),
    path('contact',views.contact,name='contact'),
    path('profile',views.profile,name='profile'),
    path('updateprofile',views.updateprofile,name='updateprofile'),
    path('events_reg',views.events_reg,name='events_reg'),
    path('password_recovery',views.password_recovery,name='password_recovery'),
    path('logout',views.logout,name='logout'),
    path('get_events',views.get_events,name='get_events'),
    path('index1',views.index1,name='index1'),
    path('adminpanel',views.a_login,name='a_login'),
    path('empanel',views.em_login,name='em_login'),
    path('viewevents',views.viewevents,name='viewevents'),
    path('viewem',views.viewem,name='viewem'),
    path('viewmessages',views.viewmessages,name='viewmessages'),
    path('viewpayments',views.viewpayments,name='viewpayments'),
    path('viewusers',views.viewusers,name='viewusers'),
    path('a_logout',views.a_logout,name='a_logout'),
    path('em_logout',views.em_logout,name='em_logout'),
    path('em_viewevents',views.em_viewevents,name='em_viewevents'),
    path('viewmyusers',views.viewmyusers,name='viewmyusers'),
    path('viewmypayments',views.viewmypayments,name='viewmypayments'),
    path('a_deleteevent/<str:e_id>/',views.a_deleteevent,name='a_deleteevent'),
    path('em_deleteevent/<str:e_id>/',views.em_deleteevent,name='em_deleteevent'),
    path('admituser/<str:email>/',views.admituser,name='admituser'),
    path('a_deleteuser/<str:email>/',views.a_deleteuser,name='a_deleteuser'),
    path('a_deleteem/<str:email>/',views.a_deleteem,name='a_deleteem'),
    path('a_deletemsg/<str:sl_no>/',views.a_deletemsg,name='a_deletemsg'),
    path('em_editevent/<str:e_id>/',views.em_editevent,name='em_editevent'),
    path('deleteprofile/<str:email>/',views.deleteprofile,name='deleteprofile'),

]
